EquipmentRentalCore/Controllers/CategorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EquipmentRentalCore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EquipmentRentalCore.Models.CategorViewModels;
using Microsoft.AspNetCore.Authorization;

namespace EquipmentRentalCore.Controllers
{
    public class CategorController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly EquipmentRentalContext _context;

        public CategorController(UserManager<User> userManager, EquipmentRentalContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string returnUrl = null, string data = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var categorList = new List<Categor>();

            if (data == null)
                categorList = await _context.Categors
                    .Include(x => x.Equipments)
                    .ToListAsync();
            else
                categorList = await _context.Categors
                    .Include(x => x.Equipments)
                    .Where(x => x.Name.Contains(data))
                    .ToListAsync();

            var elements = new List<ListCategorsModel>();
            foreach (var item in categorList)
                elements.Add(new ListCategorsModel
                {
                    Id = item.Id,
                    CategorName = item.Name,
                    EquipmentAttachedList = item.Equipments.ToList()
                });

            return View(elements);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var element = await _context.Categors.FirstOrDefaultAsync(x => x.Id.Equals(id));
            if (element != null)
            {
                var item = new ManageCategorsModel
                {
                    Id = element.Id,
                    Name = element.Name
                };
                return View(item);
            }
            else
            {
                return NotFound();
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ManageCategorsModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var elementToModify = await _context.Categors.FirstOrDefaultAsync(x => x.Id.Equals(model.Id));
                elementToModify.Name = model.Name;
                _context.Entry(elementToModify).State = EntityState.Modified;
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", "Errors during saving of elements - please check!");
            }
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Delete(int id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var elementToDelete = await _context.Categors.FirstOrDefaultAsync(x => x.Id.Equals(id));

            if (elementToDelete != null)
            {
                _context.Categors.Remove(elementToDelete);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return NotFound();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View(new ManageCategorsModel());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ManageCategorsModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var elementToAdd = new Categor
                {
                    Name = model.Name
                };
                await _context.Categors.AddAsync(elementToAdd);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string returnUrl = null)
        {
            var element = await _context.Categors
                .Include(e => e.Equipments)
                .FirstOrDefaultAsync(x => x.Id.Equals(id));

            if (element != null)
            {
                var item = new ListCategorsModel
                {
                    Id = element.Id,
                    CategorName = element.Name,
                    EquipmentAttachedList = element.Equipments.ToList()
                };
                return View(item);
            }
            else
            {
                return NotFound();
            }
        }

    }
}

EquipmentRentalCore/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EquipmentRentalCore.Models;
using EquipmentRentalCore.Models.EquipmentViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EquipmentRentalCore.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly EquipmentRentalContext _context;

        public EquipmentController(UserManager<User> userManager, EquipmentRentalContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var equipmentList = await _context
                    .Equipments
                    .Include(t => t.EquipmentType)
                    .Include(r => r.Categor)
                    .Include(ren => ren.Rental)
                    .AsNoTracking()
                    .ToListAsync();

            var equipment = new List<EquipmentListModel>();
            foreach (var item in equipmentList)
                equipment.Add(new EquipmentListModel
                {
                    Id = item.EquipmentID,
                    EquipmentName = item.EquipmentName,
                    EquipmentTypeID = item.EquipmentType.TypeID,
                    EquipmentTypeText = item.EquipmentType.TypeName,
                    CategorID = item.Categor.Id,
                    CategorName = item.Categor.Name,
                    RentID = item.Rental != null ? item.Rental.RentalID : default(int?),
                    IsRented = item.Rental != null ? true : false
                });
            return View(equipment);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var typesList = await _context.EquipmentTypes.ToListAsync();
            var categorsList = await _context.Categors.ToListAsync();
            return View(new ManageEquipmentModel(typesList, categorsList));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ManageEquipmentModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var item = new Equipment
                {
                    EquipmentName = model.EquipmentName,
                    EquipmentTypeID = model.EquipmentTypeId,
                    CategorID = model.CategorID,
                };
                await _context.Equipments.AddAsync(item);
                var res = await _context.SaveChangesAsync();
                if (res > 0)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", "Could not add element!");
            }
            var typesList = await _context.EquipmentTypes.ToListAsync();
            var categorsList = await _context.Categors.ToListAsync();
            model.EquipmentTypeList = new List<SelectListItem>();
            foreach (var item in typesList)
                model.EquipmentTypeList.Add(new SelectListItem
                {
                    Text = item.TypeName,
                    Value = item.TypeID.ToString()
                });

            model.CategorList = new List<SelectListItem>();
            foreach (var item in categorsList)
                model.CategorList.Add(new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                });
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var element = await _context.Equipments.FirstOrDefaultAsync(x => x.EquipmentID == id);
            if (element != null)
            {
                var typesList = await _context.EquipmentTypes.ToListAsync();
                var categorsList = await _context.Categors.ToListAsync();
                var item = new ManageEquipmentModel(typesList, categorsList, element.EquipmentTypeID, element.CategorID)
                {
                    EquipmentName = element.EquipmentName,
                    EquipmentId = element.EquipmentID
                };
                return View(item);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ManageEquipmentModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var element = await _context.Equipments.FirstOrDefaultAsync(x => x.EquipmentID == model.EquipmentId);
                element.EquipmentName = model.EquipmentName;
                element.EquipmentTypeID = model.EquipmentTypeId;
                element.CategorID = model.CategorID;
                _context.Entry(element).State = EntityState.Modified;
                var res = await _context.SaveChangesAsync();
                if (res > 0)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", "Could not modify element!");
            }
            var typesList = await _context.EquipmentTypes.ToListAsync();
            var categorsList = await _context.Categors.ToListAsync();

            model.EquipmentTypeList = new List<SelectListItem>();
            foreach (var item in typesList)
                model.EquipmentTypeList.Add(new SelectListItem
                {
                    Text = item.TypeName,
                    Value = item.TypeID.ToString(),
                    Selected = (item.TypeID == model.EquipmentTypeId) ? true : false
                });

            model.CategorList = new List<SelectListItem>();
            foreach (var item in categorsList)
                model.CategorList.Add(new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                    Selected = item.Id == model.CategorID ? true : false
                });
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var element = await _context.Equipments.FirstOrDefaultAsync(x => x.EquipmentID == id);
            if (element != null)
            {
                _context.Equipments.Remove(element);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var equipment = await _context
                    .Equipments
                    .Include(t => t.EquipmentType)
                    .Include(r => r.Categor)
                    .Include(ren => ren.Rental)
                    .AsNoTracking()
                    .FirstOrDefaultAsync(x => x.EquipmentID == id);

            var model = new EquipmentListModel
            {
                Id = equipment.EquipmentID,
                EquipmentName = equipment.EquipmentName,
                EquipmentTypeID = equipment.EquipmentType.TypeID,
                EquipmentTypeText = equipment.EquipmentType.TypeName,
                CategorID = equipment.Categor.Id,
                CategorName = equipment.Categor.Name,
                RentID = equipment.Rental != null ? equipment.Rental.RentalID : default(int?),
                IsRented = equipment.Rental != null ? true : false
            };
            return View(model);
        }
    }
}

EquipmentRentalCore/Views/Shared/_EmptyListModal.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Empty elements</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    No elements available
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-danger">OK</button>
    </div>
</div>

EquipmentRentalCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wypożyczalnia Turystyczna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/4f181a5240.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900&display=swap&subset=latin-ext" rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Wypożyczalnia turystyczna</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Rental" asp-action="Index">Wypożyczenia</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-original-title title>Sprzęt</a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Equipment" asp-action="Index">Sprzęt</a></li>
                            <li><a asp-area="" asp-controller="EquipmentType" asp-action="Index">Typ sprzętu</a></li>
                            <li><a asp-area="" asp-controller="Categor" asp-action="Index">Kategorie</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Group" asp-action="Index">Groups</a></li>
                </ul>
                @if (!User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Logowanie</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Rejestracja</a></li>
                    </ul>
                }
                else
                {
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="btn navbar-btn navbar-link">Witaj - @User.Identity.Name</li>
                            <li><a asp-area="" asp-controller="Account" asp-action="Manage">Zarządzaj kontem</a></li>
                            <li><input class="btn btn-link navbar-btn navbar-link" style="text-decoration:none;" type="submit" value="Logout" /> </li>
                        </ul>
                    </form>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container d-flex justify-content-end">
                <div class="container d-flex justify-content-lg-start">
                    <a class="pull-left"> <p>&copy; @DateTime.Now.Year - Wypożyczalnia Turystyczna Wiktor Winiarz</p></a>
                </div>
                <a class="pull-right" href="www.facebook.com">
                    <i class="fab fa-facebook-f fa-fw"></i>
                </a>
                <a class="pull-right" href="www.twitter.com">
                    <i class="fab fa-twitter fa-fw"></i>
                </a>
                <a class="pull-right" href="www.linkedin.com">
                    <i class="fab fa-linkedin-in fa-fw"></i>
                </a>
            </div>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>